### ISSUE TITLE
Per-snapshot widths not respected in 5.0.0.pre.4

### ISSUE THREAD

**Issue by geoffharcourt** [percy/percy-capybara#169]
Hello Percy team,

We tried to upgrade to 5.0.0.pre.4 today, but all of our mobile-only snapshots were rendering with our default width. Here's our config file (I removed the Percy CSS since it's noisy and shouldn't be relevant):

```yaml
---
version: 2

snapshot:
  widths:
    - 1370

discovery:
  network-idle-timeout: 250
  disable-cache: true

```

We added a logging statement to check our options before we took the snapshot (so one line above the snapshot call itself) in our CI process:

```
Options: {:name=>"mobile: Sign-in - en", :widths=>[411]}
--
[percy] Snapshot taken: mobile: Sign-in - en

```

All 20 of our mobile snapshots were taken at 1370px width instead of 411px despite this call (we have a helper method that sets up mobile options, so it's the same call everywhere). Can you help us figure out what's happening?
